#!/bin/bash -e

##################################################
## Author       : Shaik Saddam Hussain          ##
## Contact      : sksaddamhussain@gmail.com     ##
##################################################
## Program Name : ltracer                       ##
## Version      : 2.0                           ##
## Description  : Utility is designed to report ##
##                login related information     ##
## Release Date : 25 November 2019              ##
##################################################

# Declaration Section
LVERSION="2.0"
FILEDATE=$(date +%d%m%y%H%M%S%N)
DUMPFILE=/tmp/$HOSTNAME-ltracer-$FILEDATE
SAVEFILE=/tmp/$HOSTNAME-ltracer-$FILEDATE.csv
MAINITERATE="true"
RED='\033[0;31m'
#GREEN='\033[0;32m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
ENTRYCOUNT=0

# Initialization Section

>$DUMPFILE

print_submenu() {
        echo -e "Please select one of the following options : "
        echo -e " 1. Report ${GREEN}Active sessions${NC}"
        echo -e " 2. Report ${YELLOW}login history${NC} [ This doesn't list Active sessions ]"
        echo -e " 3. Report ${RED}Failed login${NC} Attempts\n"
}

print_mainmenu() {
        echo -e "\t\tWelcome to ${GREEN}ltracer (Login Tracer) v$LVERSION${NC}\n"
	#echo -e "${BLUE}ltracer (Login Tracer) v$LVERSION, Copyright (C) 2019 Saddam Hussain Shaik\nltracer comes with ABSOLUTELY NO WARRANTY; This is free software.${NC}\n"
	print_submenu
}

print_header() {
	echo "User Name,Source IP,TimeStamp"
}

tracerview() {
	echo ""
	cat $DUMPFILE | column -t -s',' | more
	echo ""
}

print_version() {
	echo -e "\nltracer $LVERSION (Login Tracer)"
	echo -e "Released in 2019, Author: Saddam Hussain Shaik (sksaddamhussain@gmail.com)\n"
	echo -e "ltracer comes with ABSOLUTELY NO WARRANTY; This is free software."
	echo -e "Homepage: https://github.com/sksaddamhussain/ltracer\n"
}

print_help() {
	echo -e "\nUsage: ltracer [OPTIONS]\n"
	echo -e "Uses linux kernel utilities to gather data then it is processed and formatted by utility with the feature to export the reported content in csv(comma separated values) format.\n"
	echo -e "Options:"
	echo -e "\tThis utility doesn't require any options specified to run, still you can use below options to learn more or also you can try accessing man page of ltracer by command 'man ltracer'"
	echo -e "\t--help\t\tdisplay this help and exit"
	echo -e "\t--version\toutput version information and exit\n"
	echo -e "Report ltracer translation bugs to <https://github.com/sksaddamhussain/ltracer>\n"
}

case $1 in
	''|' '|'   ')
		# Execution Section
		clear
		print_mainmenu

		while $MAINITERATE
		do
			read -p "Enter your choice : " INPUT
			case $INPUT in
				"1" | "2" | "3")
					MAINITERATE="false"
					;;
				*)
					echo -e "\n${RED}Invalid Input${NC} select from 1,2,3\n"
			esac 
		done

		case $INPUT in
			1)
				print_header > $DUMPFILE
				echo ""
				#utmpdump /var/run/utmp | grep '\[ts\/' | awk -F'[' '{print $5,$7,$9}' | sed -e 's/ ]/,/g' | tr -d ']' | tr -s ' ' | sed -e 's/ , /,/g' >> $DUMPFILE
				utmpdump /var/run/utmp | grep '\[ts\/' | awk -F'[' '{print $5,$7,$9}' | awk -F',' '{print $1,$2,$3}' | sed -e 's/ ]/,/g' | tr -d ']' | tr -s ' ' | sed -e 's/ , /,/g' >> $DUMPFILE
				ENTRYCOUNT=`utmpdump /var/run/utmp | grep '\[ts\/' | awk -F'[' '{print $5,$7,$9}' | sed -e 's/ ]/,/g' | tr -d ']' | tr -s ' ' | sed -e 's/ , /,/g' | wc -l`
				if [ $ENTRYCOUNT -eq 0 ]
				then
					echo -e "\n${RED}No data found${NC}\n"
				else
					tracerview
				fi
				;;
			2)
				print_header > $DUMPFILE
				echo ""
				#utmpdump /var/log/wtmp | grep '\[ts\/' | awk -F'[' '{print $5,$7,$9}' | sed -e 's/ ]/,/g' | tr -d ']' | tr -s ' ' | sed -e 's/ , /,/g' >> $DUMPFILE
				utmpdump /var/log/wtmp | grep '\[ts\/' | awk -F'[' '{print $5,$7,$9}' | awk -F',' '{print $1,$2,$3}' | sed -e 's/ ]/,/g' | tr -d ']' | tr -s ' ' | sed -e 's/ , /,/g' >> $DUMPFILE
				ENTRYCOUNT=`utmpdump /var/log/wtmp | grep '\[ts\/' | awk -F'[' '{print $5,$7,$9}' | sed -e 's/ ]/,/g' | tr -d ']' | tr -s ' ' | sed -e 's/ , /,/g' | wc -l`
                                if [ $ENTRYCOUNT -eq 0 ]
                                then
                                        echo -e "\n${RED}No data found${NC}\n"
                                else
                                        tracerview
                                fi
				;;
			3)
				if [ $USER != "root" ]
				then
					echo -e "\n${RED}Insufficient privilages...${NC} Please re-execute utility with ${GREEN}sudo${NC} privilage or as a ${GREEN}root${NC} user \n"
				else
					print_header > $DUMPFILE
					echo ""
					#utmpdump /var/log/btmp | grep 'ssh' | awk -F'[' '{print $5,$7,$9}' | sed -e 's/ ]/,/g' | tr -d ']' | tr -s ' ' | sed -e 's/ , /,/g' >> $DUMPFILE
					utmpdump /var/log/btmp | grep 'ssh' | awk -F'[' '{print $5,$7,$9}' | awk -F',' '{print $1,$2,$3}' | sed -e 's/ ]/,/g' | tr -d ']' | tr -s ' ' | sed -e 's/ , /,/g' >> $DUMPFILE
					ENTRYCOUNT=`utmpdump /var/log/btmp | grep 'ssh' | awk -F'[' '{print $5,$7,$9}' | sed -e 's/ ]/,/g' | tr -d ']' | tr -s ' ' | sed -e 's/ , /,/g' | wc -l`
                                	if [ $ENTRYCOUNT -eq 0 ]
                                	then
                                        	echo -e "\n${RED}No data found${NC}\n"
                                	else
                                        	tracerview
                                	fi
				fi
				;;
			*)
				echo -e "\n${RED}Invalid Input${NC}\n"
				;;
		esac

		MAINITERATE="true"
		while $MAINITERATE
		do
			if [ $ENTRYCOUNT -eq 0 ]
			then
				MAINITERATE="false"
				echo -e "Task completed... ltracer will now terminate\n"
			else	
				read -p "Would you like to SAVE the report in csv format [Y/N] : " REPORT
	
				case $REPORT in
					y | Y | Yes | YES | yes)
						cp $DUMPFILE $SAVEFILE
						sed -e 's/\t/,/g' -i $SAVEFILE
						echo -e "Report is saved at $SAVEFILE"
						echo -e "Task completed... ltracer will now terminate\n"
						MAINITERATE="false"
						;;
					n | N | No | NO | no)
						MAINITERATE="false"
						echo -e "Task completed... ltracer will now terminate\n"
						;;
					*)
						echo -e "\n${RED} Invalid Input${NC} select from Y,N \n"
						;;
				esac
			fi
		done
		;;
	"-V"|"-v"|"--version")
		print_version
		;;
	*)
		print_help
		;;
esac

# Clean up section
rm -rf $DUMPFILE

